apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rc-announcer.fullname" . }}
  labels:
    app: {{ template "rc-announcer.name" . }}
    chart: {{ template "rc-announcer.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  rc-user-authtoken: {{ .Values.rocketchat.RC_AUTH_TOKEN | b64enc | quote }}